#!/bin/bash

pid=''

function getProcess(){
    process=$(ps ax |grep aria2c | grep -v grep)
    
    if [[ -n $process ]];then
        pid=$(echo $process | awk '{print $1;}')
    fi
}

function start(){
    if [[ -n $pid ]];then
        echo "process already exist:"$pid
        exit 1
    fi

    conf=$( cd "$(dirname $0)" && pwd)'/aria2.conf'
    /usr/local/bin/aria2c --conf-path=$conf -D

    getProcess
    if [[ -n $pid ]];then
        echo "process start ok: "$conf
    else
        echo "start failed, please check the reason"
    fi
}

function stop(){
    if [[ -z $pid ]];then
        echo "no aria2c process found"
    else
        kill -9 $pid
        echo $pid" is killed"
    fi
}
function usage(){
    if [[ -n $pid ]];then
        echo "aria2c exist and pid is: "$pid
    fi

    echo "Usage: $0 start|stop"
    exit 1
}

getProcess

if [[ $1 = 'start' ]];then
    start
elif [[ $1 = 'stop' ]];then
    stop
else
    usage
fi


