#! /bin/sh
### BEGIN INIT INFO
# Provides:          sungeo
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run sungeo SMS sending service exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
	if [ -x /opt/zeromq/shell/queue/start.sh ]; then
	        [ "$VERBOSE" != no ] && log_begin_msg "Running local boot scripts (/opt/zeromq/shell/queue/start.sh)"
		/opt/zeromq/shell/queue/start.sh
		ES=$?
		[ "$VERBOSE" != no ] && log_end_msg $ES
		return $ES
	fi
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
